"""Add target params

Revision ID: 0afeb320f024
Revises: 
Create Date: 2026-06-28 08:29:41.309364
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0afeb320f024'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'assets', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'pipeline_runs', 'projects', ['project_id'], ['id'])
    op.add_column('projects', sa.Column('target_duration', sa.String(length=20), nullable=False))
    op.add_column('projects', sa.Column('target_quality', sa.String(length=20), nullable=False))
    op.add_column('projects', sa.Column('target_style', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'target_style')
    op.drop_column('projects', 'target_quality')
    op.drop_column('projects', 'target_duration')
    op.drop_constraint(None, 'pipeline_runs', type_='foreignkey')
    op.drop_constraint(None, 'assets', type_='foreignkey')
    # ### end Alembic commands ###
